version: 2

project_name: intsdk

builds:
  - id: linux
    binary: intsdk
    main: ./src
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: darwin
    binary: intsdk
    main: ./src
    goos: [darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: windows
    binary: intsdk
    main: ./src
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README*
      - data/kestby.toml

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"